services:
  backend:
    build:
      context: ./back
    environment:
      - APP_ENV=${APP_ENV}
      - APP_CORS_ORIGINS=${APP_CORS_ORIGINS}
    env_file:
      - .env
    volumes:
      - ./back/sats.db:/app/back/sats.db

  frontend:
    build:
      context: ./front
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WEBSITE_URL=${NEXT_PUBLIC_WEBSITE_URL}
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WEBSITE_URL=${NEXT_PUBLIC_WEBSITE_URL}
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend