"""Softwarecontract2

Revision ID: 03cc5520fd23
Revises: a70d273263ef
Create Date: 2025-01-25 18:30:02.361171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cc5520fd23'
down_revision: Union[str, None] = 'a70d273263ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.drop_column('software', 'contract_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('contract_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'software', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
