"""EquipmentStatusFixes

Revision ID: 10f938cf108f
Revises: 6c33a1ee9fee
Create Date: 2025-02-02 01:52:46.469534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f938cf108f'
down_revision: Union[str, None] = '6c33a1ee9fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_statuses', 'doc_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment_statuses', 'responsible_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment_statuses', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_statuses', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment_statuses', 'responsible_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment_statuses', 'doc_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
