"""ResponsibleUserJob/Office

Revision ID: 116182a2a4d1
Revises: 03cc5520fd23
Create Date: 2025-02-01 21:35:31.329663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116182a2a4d1'
down_revision: Union[str, None] = '03cc5520fd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_user_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )

    op.create_table('responsible_user_offices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_name')
    )

    # Используем batch_alter_table для поддержки SQLite
    with op.batch_alter_table('responsible_users') as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('office_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_responsible_users_job', 'responsible_user_jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key('fk_responsible_users_office', 'responsible_user_offices', ['office_id'], ['id'])
        batch_op.drop_column('job')
        batch_op.drop_column('office')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsible_users') as batch_op:
        batch_op.add_column(sa.Column('office', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('job', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_responsible_users_office', type_='foreignkey')
        batch_op.drop_constraint('fk_responsible_users_job', type_='foreignkey')
        batch_op.drop_column('office_id')
        batch_op.drop_column('job_id')

    op.drop_table('responsible_user_offices')
    op.drop_table('responsible_user_jobs')
    # ### end Alembic commands ###
