"""Backup changed added smb fields

Revision ID: 4983c4d6b518
Revises: c8668140125c
Create Date: 2026-02-05 11:25:07.211141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4983c4d6b518'
down_revision: Union[str, None] = 'c8668140125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_auto_settings', sa.Column('smb_username', sa.String(), nullable=True))
    op.add_column('backup_auto_settings', sa.Column('smb_password', sa.String(), nullable=True))
    op.add_column('backup_auto_settings', sa.Column('smb_ip', sa.String(), nullable=True))
    op.add_column('backup_auto_settings', sa.Column('smb_dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup_auto_settings', 'smb_dir')
    op.drop_column('backup_auto_settings', 'smb_ip')
    op.drop_column('backup_auto_settings', 'smb_password')
    op.drop_column('backup_auto_settings', 'smb_username')
    # ### end Alembic commands ###
