"""EquipmentSpecs2

Revision ID: 4ffb239f7e61
Revises: 0324decfec04
Create Date: 2025-02-02 01:23:04.706687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffb239f7e61'
down_revision: Union[str, None] = '0324decfec04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_specifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('screen_resolution', sa.String(), nullable=True),
    sa.Column('processor_type', sa.String(), nullable=True),
    sa.Column('ram_size', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('storage_size', sa.String(), nullable=True),
    sa.Column('gpu_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_specifications')
    # ### end Alembic commands ###
