"""Add color to status type

Revision ID: 5ce3ddef1e1e
Revises: 824ae94413be
Create Date: 2025-02-16 18:20:46.631606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce3ddef1e1e'
down_revision: Union[str, None] = '824ae94413be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_status_types', sa.Column('status_type_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_status_types', 'status_type_color')
    # ### end Alembic commands ###
