"""EquipmentSpecs3

Revision ID: 6c33a1ee9fee
Revises: 4ffb239f7e61
Create Date: 2025-02-02 01:28:29.809312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c33a1ee9fee'
down_revision: Union[str, None] = '4ffb239f7e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_specifications', sa.Column('storage', sa.String(), nullable=True))
    op.drop_column('equipment_specifications', 'storage_type')
    op.drop_column('equipment_specifications', 'storage_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_specifications', sa.Column('storage_size', sa.VARCHAR(), nullable=True))
    op.add_column('equipment_specifications', sa.Column('storage_type', sa.VARCHAR(), nullable=True))
    op.drop_column('equipment_specifications', 'storage')
    # ### end Alembic commands ###
