"""Add accepted_date column

Revision ID: 824ae94413be
Revises: c0ddfec04888
Create Date: 2025-02-16 17:46:59.141880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824ae94413be'
down_revision: Union[str, None] = 'c0ddfec04888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('accepted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'accepted_date')
    # ### end Alembic commands ###
